# Site Settings
title: 						"Bytemaster's Blog"
description: 				"My name is Daniel Larimer and I am the founder of BitShares. My mission in life is to find free market solutions to secure life, liberty, and property for all."
baseurl: 					""
#url: 						""
logourl: 					"/assets/img/bloglogo.jpg"		
fa-logo: 					"fa-bold"
paginate: 				10	


# Author Settings
author_name: 				"Daniel Larimer"
#author_url: 				"http://bitshares.org"
author_bio: 				"My name is Daniel Larimer and I am the founder of BitShares. My mission in life is to find free market solutions to secure life, liberty, and property for all."

author_image: 			"/assets/img/author-dan.jpg"




# Social Settings
#twitter_url: 				"http://twitter.com"
#facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com/bytemaster"
#youtube_url:  				"http://youtube.com"
#dribbble_url:  				"http://dribbble.com"
#googleplus_url: 			"http://google.com/plus"
#instagram_url:  			"http://instagram.com"
#pinterest_url:  			"http://pinterest.com"
#linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"thebytemaster"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28282324-1"
theme_analytics_domain: 	""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		true


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

